//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackBoss.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caboose
    {
        public long ID { get; set; }
        public string UniqueId { get; set; }
    
        public virtual ScaleData ScaleData { get; set; }
        public virtual CupolaType CupolaType { get; set; }
        public virtual RollingStock RollingStock { get; set; }
    }
}
