//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackBoss.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.CarAssignedCommodities = new HashSet<CarAssignedCommodity>();
        }
    
        public long ID { get; set; }
        public string UniqueId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarAssignedCommodity> CarAssignedCommodities { get; set; }
        public virtual LoadsEmpty LoadsEmpty { get; set; }
        public virtual ScaleData ScaleData { get; set; }
        public virtual CarType CarType { get; set; }
        public virtual RollingStock RollingStock { get; set; }
    }
}
