//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackBoss.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePrintOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServicePrintOption()
        {
            this.Services = new HashSet<Service>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CrewPrintLogicEnum { get; set; }
        public Nullable<long> ConsistPrintLogicEnum { get; set; }
        public Nullable<bool> YardMustReleaseConsist { get; set; }
    
        public virtual AliasPrinter AliasPrinter { get; set; }
        public virtual AliasPrinter AliasPrinter1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Services { get; set; }
    }
}
