//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackBoss.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceExtraBoardLogic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceExtraBoardLogic()
        {
            this.ServiceExtraBoardAssignedAttributes = new HashSet<ServiceExtraBoardAssignedAttribute>();
            this.Services = new HashSet<Service>();
        }
    
        public long ID { get; set; }
        public bool OriginTrackMustBeFull { get; set; }
        public Nullable<long> PriorityRatioAntecedent { get; set; }
        public Nullable<long> PriorityRatioConsequent { get; set; }
        public Nullable<long> ExtraBoardLogicYardRequestOptionsEnum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceExtraBoardAssignedAttribute> ServiceExtraBoardAssignedAttributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Services { get; set; }
    }
}
