//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackBoss.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WheelArrangement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WheelArrangement()
        {
            this.ServiceApplicationLocomotiveLogics = new HashSet<ServiceApplicationLocomotiveLogic>();
            this.ServiceApplicationLocomotiveLogics1 = new HashSet<ServiceApplicationLocomotiveLogic>();
            this.ServiceApplicationLocomotiveLogics2 = new HashSet<ServiceApplicationLocomotiveLogic>();
            this.RollingStocks = new HashSet<RollingStock>();
        }
    
        public long ID { get; set; }
        public long WheelArrangementTypesEnum { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceApplicationLocomotiveLogic> ServiceApplicationLocomotiveLogics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceApplicationLocomotiveLogic> ServiceApplicationLocomotiveLogics1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceApplicationLocomotiveLogic> ServiceApplicationLocomotiveLogics2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RollingStock> RollingStocks { get; set; }
    }
}
