//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackBoss.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class YardStagingTrack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YardStagingTrack()
        {
            this.StagingTrackAssignedHomeRoads = new HashSet<StagingTrackAssignedHomeRoad>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CompletionActionEnum { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StagingTrackAssignedHomeRoad> StagingTrackAssignedHomeRoads { get; set; }
        public virtual Track Track { get; set; }
        public virtual YardTrack YardTrack { get; set; }
    }
}
