//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackBoss.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class YardBlockTrack
    {
        public long ID { get; set; }
        public Nullable<bool> PreassignDestination { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual YardTrack YardTrack { get; set; }
    }
}
