//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackBoss.Data
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;

    public partial class Yard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yard()
        {
            this.MultiSwitchers = new ObservableCollection<MultiSwitcher>();
            this.YardTracks = new ObservableCollection<YardTrack>();
        }
    
        public long ID { get; set; }

        public string UniqueId { get; set; }
        public Nullable<bool> HasMultiSwitchers { get; set; }
        public Nullable<bool> HasArrivalTracks { get; set; }
        public Nullable<bool> HasDepartureTracks { get; set; }
        public Nullable<bool> HasThruTracks { get; set; }
        public Nullable<bool> PassengerStation { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual /*ICollection*/ObservableCollection<MultiSwitcher> MultiSwitchers { get; set; }
        public virtual Site Site { get; set; }
        public virtual Switcher Switcher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual /*ICollection*/ObservableCollection<YardTrack> YardTracks { get; set; }
    }
}
